### ISSUE TITLE
Info command auf hübsches Embed umstellen

### ISSUE THREAD

**Issue by tobi6112** [NullDev/CSC-Bot#129]
Der schickt derzeit eine PN an den User. Mit Slash Commands würde ich da aber lieber ein fancy Embed anzeigen wollen. Vielleicht kannst du mal ein hübsches Embed designen, was in den Channel geschrieben wird. 
Du kannst dafür Tools  nutzen wie https://autocode.com/tools/discord/embed-builder/ oder https://leovoel.github.io/embed-visualizer/ um grob das Layout zu machen. 

Also:
1. Schritt: Layout des Embdes festlegen
2. Schritt: Bestehenden Code abändern, dass das Embed gesendet wird

**Comment by KugelPfusch** [comment]
Ich mache es!
