### ISSUE TITLE
Update DevContainer

### ISSUE THREAD

**Issue by tobi6112** [NullDev/CSC-Bot#130]
Die `streetsidesoftware.code-spell-checker-german` wird vor der `streetsidesoftware.code-spell-checker` geladen und funktioniert daher nicht. in der `devcontainer.json` muss die Reihenfolge geändert werden.

Ansonsten wäre es noch cool, wenn jemand das Ding rund machen würde, notwendige Settings für Formatting, linting, etc. pp alles was notwendig ist mit reinklatscht. Referenz: <https://code.visualstudio.com/docs/remote/devcontainerjson-reference>

Vorschlag von meiner Seite: SonarLint Extension sollte mit rein.

**Comment by Faro1991** [comment]
Schnapp ich mir, kann aber etwas länger dauern als der Rest^^
