### ISSUE TITLE
Auf Slash commands umbauen

### ISSUE THREAD

**Issue by tobi6112** [NullDev/CSC-Bot#35]
https://discord.com/developers/docs/interactions/slash-commands

Den Bot auf Slash Commands umbauen.
- Jeder Command one by one
- Oder als seperate branch bis alle durch sind

Reactions dabei mit den neuen Nativen Buttons ersetzen (Kein Rate Limit für bots mehr etc, aka buttons erscheinen instant)

**Comment by NullDev** [comment]
Wo umbau

**Comment by diewellenlaenge** [comment]
Ja gut, ich mach ja schon weiter.

**Comment by diewellenlaenge** [comment]
Bitte erstmal nicht anfassen im Rahmen von Hacktoberfest. Bitte nur in Rücksprache mit `diewellenlaenge`. Danke!

**Comment by diewellenlaenge** [comment]
Abandoned in favor of #114 bzw. https://github.com/NullDev/CSC-Bot/projects/1
