### ISSUE TITLE
.extend soll die letzte Umfrage im Channel targeten

### ISSUE THREAD

**Issue by NullDev** [NullDev/CSC-Bot#36]
## Funktions Wunsch

**Funktionen:** <br>
.extend soll die letzte Umfrage im Channel targeten wenn man die Nachricht nicht als Reply sendet.

CC: @diewellenlaenge

**Comment by diewellenlaenge** [comment]
Ich bin aus folgenden Gründen dagegen:

- Menschen sind dumm und vergesslich. Wenn jemand eine Umfrage sieht, die extendable ist und NICHT die letzte Umfrage ist, z. B. weil er hochgescrollt hat, wird eine falsche Umfrage erweitert
- Wenn jemand eine Umfrage sieht und denkt sie ist extendable (obwohl sie es nicht ist), wird die Erweiterung der letzten extendable Umfrage hinzugefügt und nicht zu der, die eigentlich mental gemeint war

**Comment by holzmaster** [comment]
Sehe ich auch so

**Comment by NullDev** [comment]
ogeh
