### ISSUE TITLE
Cron tut bei falscher zeit cron senden tun

### ISSUE THREAD

**Issue by NullDev** [NullDev/CSC-Bot#60]
![image](https://user-images.githubusercontent.com/22935000/126489603-d6e37c89-7f12-43b6-8871-a6209f21e133.png)

des muss da so um 13:37 sein und ned 14:37.

@NullDev dein """fix""" hier:
https://github.com/NullDev/CSC-Bot/blob/master/src/app.js#L78
hats ja voll gebracht. nicht. spasst. 

pls fix kthxbye

**Comment by NullDev** [comment]
@jonas32 pls fix

**Comment by diewellenlaenge** [comment]
Please comment on my solution! 22b15450e21df26996835978969ded391eb3266b
