### ISSUE TITLE
Bot kaputt

### ISSUE THREAD

**Issue by Feluin** [NullDev/CSC-Bot#69]
![image](https://user-images.githubusercontent.com/20358156/130287746-75a4211c-8b0b-4675-af31-23619a7f0f87.png)

Unbenutzbar. würde Geld zurückverlangen-

**Comment by nimbl0** [comment]
Wie behindert seid ihr?

Alle so: Ja

**Comment by tobi6112** [comment]
Gefixt mit c185f8e58b768d39dac4910eea4c751757ba0272
