### ISSUE TITLE
Metafrage Command

### ISSUE THREAD

**Issue by tobi6112** [NullDev/CSC-Bot#81]
## Funktions Wunsch

**Funktionen:** <br>
Command gegen Metafragen, warum doof, warum besser nicht. Link zu http://metafrage.de/ und Zusammenfassung als Nachricht.

Wenn man ganz fancy sein möchte vielleicht automatische Erkennung solcher Fragen durch die üblichen "Kennt sich jemand ...", "Jemand Ahnung von ..." Floskeln.

**Comment by Faro1991** [comment]
Schnapp ich mir mal :)
