### ISSUE TITLE
Mehr Umfrageoptionen erlauben

### ISSUE THREAD

**Issue by tobi6112** [NullDev/CSC-Bot#82]
## Funktions Wunsch

**Funktionen:** <br>
Im Moment gehen nur 10 Umfrageoptionen. Wir wollen mehr. Also erweitern mit den Buchstaben A-Z. Beachte maximale Anzahl an Reactions und Zeichenlimit in Embeds.

**Comment by nimbl0** [comment]
Hamlo, I will die Umfrageoptionen machern
