### ISSUE TITLE
Erweiterbare Umfragen mit einer Option erlauben

### ISSUE THREAD

**Issue by tobi6112** [NullDev/CSC-Bot#83]
## Funktions Wunsch

**Funktionen:** <br>
Erweiterbare Umfragen sollen auch mit einer vorgegebenen Antwortmöglichkeit erstellbar sein.

`.poll -e Ich heiße ...; Klaus Peter` erlaubt
`.poll -s Ich heiße ...; Klaus Peter` nicht erlaubt

**Comment by s0LA1337** [comment]
Mach ich :)
