### ISSUE TITLE
Tweak Prune 

### ISSUE THREAD

**Issue by tobi6112** [NullDev/CSC-Bot#84]
## Funktions Wunsch

**Funktionen:** <br>
> Bot Vorschlag: (ich bin faul soll n anderer machen).
> In 📖┃regeln-und-faq steht aktuell
> Um die anderen Channel sehen zu können, müssen Sie unseren AGB's zustimmen. Sollten Sie dies nicht innerhalb von 48h tun, werden Sie automatisch gekickt.

> das ist leider nicht ganz korrekt. Der Bot macht täglich nen prune für leute die 2tage / 48h inaktiv waren und keine rollen haben. hier:

> https://github.com/NullDev/CSC-Bot/blob/master/src/app.js#L68-L76

> Das bedeutet aber wenn die keine rollen haben aber auf discord trotzdem aktiv sind, werden die nie weg gepruned und bleiben (für uns inaktiv) weiterhin hier.

> Deshalb request: Bot soll alle jockel die zwei tage nach joinen immer noch keine nerd rolle haben, kicken.
(Im 13:37 cron alle member mit ohne nerd-rolle auflisten und wenn (datetime.now - join.timestamp) > 48h -> kick)

**Comment by KugelPfusch** [comment]
Ich probiere es!
