### ISSUE TITLE
Stempelkarte (Schritt 1: Stempeln)

### ISSUE THREAD

**Issue by tobi6112** [NullDev/CSC-Bot#85]
## Funktions Wunsch

**Funktionen:** <br>
Wir machen eine Stempelkarte wie beim Dönermann. Erster Schritt das Stempeln an sich.
Also wir brauchen einen Mod Command, nennen wir ihn mal `~stempel` damit kann ich für einen User einen bestimmten Invite stempeln. Das wird dann über unsere Tolle SQLite Datenbank gespeichert. 

Als direktes Beispiel: 
`~stempel @UserA @UserB`
würde bedeuten, dass der UserA UserB invited hat und einen Stempel dafür bekommt. 
Wichtig ist jetzt, dass ein User nicht mehrfach gestempelt werden kann (Constraints und so blabla).

Wichtige Attribute, die in der Datenbank liegen müssen:
Zeitpunkt des Stempelns
User-ID Inviter
User-ID Invite

**Comment by nimbl0** [comment]
assign me pls daddy

**Comment by nimbl0** [comment]
Würde ich auch mal machen
