### ISSUE TITLE
Stempelkarte (Schritt 2: Die Stempelkarte)

### ISSUE THREAD

**Issue by tobi6112** [NullDev/CSC-Bot#86]
## Funktions Wunsch

**Vorraussetzung:**
#85 

**Funktionen:** <br>
Command `.stempelkarte` zeigt die persönliche Stempelkarte an. Sprich wie viele User invited wurden.
Jetzt wäre es sexy, wenn das nicht schnöde als Text ausgegeben wird, sondern ein Bild generiert wird oder irgendwie sowas. Keine Ahnung, das Issue ist nicht sonderlich durchdacht. Lasst eure Kreativität spielen. Ein Vorschlag ist hier zu finden: https://cdn.discordapp.com/attachments/620753789598564352/862963212010258432/image.png

**Comment by holzmaster** [comment]
Ich würd mir das mal angucken.
