### ISSUE TITLE
Update discord.js

### ISSUE THREAD

**Issue by diewellenlaenge** [NullDev/CSC-Bot#87]
discord.js ist alt. Muss neu (am besten auf einen Tag binden relativ aktuell mit Support für Slashcommands, Menus, Buttons etc.).

Problem: das Update hat breaking changes. Daher ist ein einfaches pullen von discord.js nicht ausreichend.

**Comment by tobi6112** [comment]
Als Ergänzung hierzu. AFAIK ist der einzige relevante Breaking Change, dass wir die Gateway Intents spezifizieren müssen:

Das heißt entweder explizit:
```js
const client = new Discord.Client({ intents: [Discord.Intents.FLAGS.GUILDS, Discord.Intents.FLAGS.GUILD_MEMBERS, Discord.Intents.FLAGS.GUILD_INTEGRATIONS, Discord.Intents.FLAGS.GUILD_MESSAGES, Discord.Intents.FLAGS.GUILD_MESSAGE_REACTIONS, Discord.Intents.FLAGS.DIRECT_MESSAGES] });
```
Oder einfach yolo alle:
```js
const client = new Discord.Client({ intents: [Discord.Intents.ALL] });
```

https://github.com/diewellenlaenge/CSC-Bot/blob/slash-commands-ts/src/app.js#L49
