### ISSUE TITLE
Zitate in Zitatechannel

### ISSUE THREAD

**Issue by diewellenlaenge** [NullDev/CSC-Bot#88]
## Funktionswunsch

**Funktionen:**
"Wertvolle" bzw. lustige Nachrichten sollen im Channel `#zitate` (`888414626734280825`). Dafür sollten alle Trusted-Leute eine Berechtigung haben, eine bestimmte Reaction auf eine Nachricht zu setzen. Sobald diese Reaction auf eine Nachricht gesetzt wurde, soll der Bot die Nachricht vernünftig formatiert mit einer Referenz auf die Originalnachricht in den o. g. Channel packen.

**Todos:**

- Reaction hochladen und vernünftig benennen
- Reaction-Handler bauen
- Rechteprüfung auf Trusted
- Jemanden beleidigen, der die Reaction nutzt aber nicht darf
- Sollte die Nachricht aus einem dieser Channel kommen, dann soll die Nachricht anonym zitiert werden (mit Referenz aber ohne Nickname):
  - Gründerväter: `675723082073243648`
  - Intern: `620734386639339520`

**Weitere Diskussion:**
Bitte hier lesen: https://discord.com/channels/618781839338897443/620753789598564352/821657478521159741

**Comment by j-brn** [comment]
👀

**Comment by tobi6112** [comment]
> 👀

Mach mal nicht nur Auge, mach mal was
